# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6f235e8eda986ecf2446cf564256cb1a79fd2bce2c51b9f40929211a08097dffc4f4bfff5a6f0e7ef8efc8069b6d397c5cb6bd7b2c66065848a5d7d7e0664a1

test:
  secret_key_base: 14eb0d9e1a26cb38150d4f594d3842fb7cabedf2817f93e7be581bf9d49f07f0190f5842de324ec600f1a2168f6f798ca6bab47cdb73f37f64b08d97f8bbd272

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
